### ISSUE TITLE
missing translations for charger types in settings

### ISSUE THREAD

**Issue by rowich** [Iternio-Planning-AB/abrp-translations#16]
The selection for "Tesla CCS" results in displaying "tesla_ccs" in german (with an underline). I did not found any translatable items for this section in the text file (nor in the EN one, which behaves similar).

Also, I was wondering about the displayed selection "SC" - which is (all from my point of view) the acronym for "Service Center", not Supercharger, which should be "SuC"

Nothing important at all.
![image](https://user-images.githubusercontent.com/49855876/79684797-6a352700-8234-11ea-98b5-2d8b66a676e3.png)

**Comment by iternio** [comment]
Thanks, we'll fix that!

**Comment by TomTomZoe** [comment]
Meanwhile issue is fixed and can be closed.
