### ISSUE TITLE
Missing translation in da.json

### ISSUE THREAD

**Issue by swesterhoff** [Iternio-Planning-AB/abrp-translations#249]
I can't seem to find the lines to translate follwing: 
The "automotive" and "Generic" section.
The "amenity" section, (can't change the "h" and "m" - time)
ABRP Premium-membership (can't change the "Prev" and "Next" under the pictures).

I have not bought the premium version yet.
Maybe there are more shortcomings when I get it activated

**Comment by iternio** [comment]
Swesterhoff - please send us a mail at contact@iternio.com and we can arrange a premium membership for you as a thank you for translating.

**Comment by TomTomZoe** [comment]
I almost become envious ;-), unfortunately I was already a premium member when I started to actively work on the translations and improve them.

**Comment by iternio** [comment]
I think we can arrange that too - send us an email!

Best / Bo

Bo Lincoln, PhD, CEO
Iternio Planning AB
