### ISSUE TITLE
Missing translation in weather settings

### ISSUE THREAD

**Issue by TomTomZoe** [Iternio-Planning-AB/abrp-translations#26]
I've found no translation for the wind settings HEAD and TAIL, neither in de.json nor in en.json.
It would be nice if this little text would also be language specific :-)

![Head](https://user-images.githubusercontent.com/66869770/84873047-ee642900-b082-11ea-9254-b7cc6837e92e.JPG)
![Tail](https://user-images.githubusercontent.com/66869770/84873057-f02dec80-b082-11ea-99c3-30e43762c904.JPG)

**Comment by PomkHU** [comment]
Same for the hungarian translation.
I suppose these are functional buttons which are not part of the language file like the "FOR" and "TO".

**Comment by knowbody** [comment]
closing as this is now possible to translate and translated
