### ISSUE TITLE
Copy of de.json and en.json with extension .orig

### ISSUE THREAD

**Issue by TomTomZoe** [Iternio-Planning-AB/abrp-translations#423]
Recently there is a copy of the German and English language file with the extension .orig.
[de.json.orig](https://github.com/Iternio-Planning-AB/abrp-translations/blob/master/de.json.orig)
[en.json.orig](https://github.com/Iternio-Planning-AB/abrp-translations/blob/master/en.json.orig)

@iternio, @knowbody 
What is the intention behind this?

**Comment by knowbody** [comment]
good question, probably some artefacts of our script. will get them removed before the next release
