### ISSUE TITLE
Missing translation option for "Adjust to" for proposed maximum speed on CarPlay Display

### ISSUE THREAD

**Issue by TomTomZoe** [Iternio-Planning-AB/abrp-translations#456]
ABRP v4.3.9 (2124)
iPhone 12 Pro iOS 16.3.1

The text "Adjust to" for proposed maximum speed on CarPlay Display is not translatable. There's no string for translation.

![IMG_3148](https://user-images.githubusercontent.com/66869770/228464162-2c02b805-d4c5-481c-a4de-e1145ff390aa.PNG)

**Comment by TomTomZoe** [comment]
Still same issue with ABRP V4.4.4 (2291)

**Comment by knowbody** [comment]
this is on purpose as translating it would cause UI issues having in mind that the text might be longer for some languages. For now it will stay like this.
