### ISSUE TITLE
Missing translation option for Apple Watch UI

### ISSUE THREAD

**Issue by TomTomZoe** [Iternio-Planning-AB/abrp-translations#491]
ABRP v4.4.1
iPhone 12 Pro iOS 16.5
Apple Watch

The GUI texts for Apple Watch are not translatable. There are no strings for translation.

![INCOMING-86B7A060-37D9-4CEB-ADFF-4D76A167FF64](https://github.com/Iternio-Planning-AB/abrp-translations/assets/66869770/0d6bd224-5ee3-47b0-b4f8-daa3b47deca8)

**Comment by knowbody** [comment]
for now we do not support translations on Apple Watch. but I will add it as a `feature request`
