### ISSUE TITLE
Rate a charger

### ISSUE THREAD

**Issue by swesterhoff** [Iternio-Planning-AB/abrp-translations#533]
There's a problem with the popup window for the rating of a charger.
It still says: "Yes", "Maybe", and "No", in the translation.
Some strings may be missing in the translation files, or a bug in the code.
![image](https://github.com/Iternio-Planning-AB/abrp-translations/assets/102220554/a118bc93-fb81-4a22-93c5-80bbf72524ca)

The language doesn't matter, same issue in German.

**Comment by Palm35** [comment]
The language doesn't matter, same issue in French

**Comment by knowbody** [comment]
I will add those to the translation files for the next release

**Comment by knowbody** [comment]
fixed, so the translations can be added now

**Comment by Palm35** [comment]
Ok last french translation 4.5.0 done
