### ISSUE TITLE
identifier “notiffication_settings” seems to be written incorrectly

### ISSUE THREAD

**Issue by TomTomZoe** [Iternio-Planning-AB/abrp-translations#764]
It is possible that the identifier “notiffication_settings” (with two f) is not used in the app V4.8.0, as it is called “notification_settings” (with one f) in the source code of the app?

**Comment by knowbody** [comment]
it is used, I'd rather keep it as is for now. changing the name of the key will cause issues with the current translations. the key name has no effect on anything otherwise
