### ISSUE TITLE
Settings in new dialog "Charging stops" is not translatable into local language

### ISSUE THREAD

**Issue by TomTomZoe** [Iternio-Planning-AB/abrp-translations#815]
The settings in the new "Charging stops" dialogue cannot be translated into german, and certainly not in other languages.
This affects the translation of "Few but long stops", "Quickest arrival’ and "Short but many stops"

![Charging Stops](https://github.com/user-attachments/assets/829be975-c83e-488a-9681-c7cab2963416)
.

**Comment by knowbody** [comment]
this should use the: `charge_break_preference_least_time` key, probably the issue in our codebase. Thank you for reporting it!

**Comment by TomTomZoe** [comment]
This issue is fixed now in ABRP V5.0.7, thanks a lot!

**Comment by TomTomZoe** [comment]
Can be closed.
